-- 코드를 입력하세요
SELECT HOUR(DATETIME) AS OUR, COUNT(*)
FROM ANIMAL_OUTS
GROUP BY OUR
HAVING OUR BETWEEN 9 AND 19
ORDER BY OUR;

SELECT HOUR(DATETIME) AS HOUR, COUNT(*)
FROM ANIMAL_OUTS
GROUP BY HOUR
HAVING HOUR BETWEEN 9 AND 19
ORDER BY HOUR